//
// Created by tomek on 26.04.2022.
//

#ifndef PROI_PROJEKT_EVENT_H
#define PROI_PROJEKT_EVENT_H

#include <exception>
#include <string>
#include <memory>

class Tank;

class Grid;

/**
 * Indicates an error encountered while constructing an Event instance.
 */
struct EventConstructionException : public std::exception {
    [[nodiscard]] const char * what () const noexcept override;
};

/**
 * \brief Represents a single event of type Event::EventType
 *
 * Event types are represented with EventType enum. EventType always needs to be passes to constructor, followed
 * by appropriate args. If incorrect args are provided, an EvenConstructionException is thrown.
 *
 * Event class has multiple constructor that can be used for initializing different events.
 *
 * Events can be generated by any classed and should be passed to an event queue (./EventQueue.h)
 */
class Event {
public:

    /**
     * Represents event types
     */
    enum EventType {  // TODO make Event an abstract base class; move enum to separate file and specify enum values there (EVENT SHOULD KNOW EVENT TYPE TO STORE IT)
        NullEvent = 0,

        KeyPressed,
        KeyReleased,

        TankSpawned,  // TODO replace with entity (not necessary if enum was moved to separate file)
        TankKilled,
        TankMoved,
        TankRotated,
        TankHit,
        TankRemoved,

        TilePlaced,
        TileChanged,
        TileDeleted,

        LevelBuilt
    };

    EventType type;

    /**
     * Holds additional event info for keyboard related events
     */
    struct KeyEventInfo {
        enum KeyAction{
            Pressed =0,
            Released
        };
        unsigned int keyCode;
        KeyAction action;
    };

    /**
     * Holds additional event info for tank related events
     * If an event was created as a result of deleting a tank, member variable
     * will point to deallocated memory and should only be used for removing empty
     * references in other objects
     * TRYING TO ACCESS MEMBER VARIABLE'S ATTRS WILL RESULT IN UNDEFINED BEHAVIOR
     */
    struct TankInfo {  //
        Tank* tank;  // FIXME WILL POINT TO DEALLOCATED MEMORY IF TANK WAS DELETED (create a separate struct with unique_ptr or only pass deleted tank attrs)
    };

    struct TileInfo {
        unsigned int tile_x;
        unsigned int tile_y;
        Grid* grid;
    };

    struct LevelInfo {
        unsigned int levelNumber;
        Grid* grid;
    };

    // ####################################################3
    /**
     * Contains additional event info.
     * Unions member is initialized according to EventType enum passed to the constructor
     * Trying to access any member other than initialized will result in undefined behavior
     */
    union info_u {
        KeyEventInfo keyInfo;
        TankInfo tankInfo;
        TileInfo tileInfo;
        LevelInfo levelInfo;

        ~info_u(){};  // DO NOT change this to =default, or else it will stop working
    } info = {};

    // FIXME not so elegant
    Event(EventType, unsigned int ui1);

    explicit Event(EventType);

    Event(EventType e, Tank* tank);

    Event(EventType e, unsigned int x, unsigned int y, Grid* grid);

    Event(EventType e, unsigned int levelNumber, Grid* grid);

    Event()=delete;
};


#endif //PROI_PROJEKT_EVENT_H
